"""Execution input integrity, limited to H1 population semantics and conversion."""
from dataclasses import dataclass, field
from hashlib import sha256
import json
from numbers import Real

import numpy as np
import pandas as pd

from app.schemas.capability import (
    AuthoritativeInputFingerprint, ColumnProvenance, ConversionNormalizationPolicy,
    ConversionNormalizationRecord, DatasetInputFingerprint, DatasetSemanticState,
    OperatorParameters, VersionedDatasetRef,
)
from app.services.conversion_diagnosis_service import DiagnosisError

NORMALIZATION_POLICY = ConversionNormalizationPolicy()
READER_CONTRACT = "capability-logical-reader@1"
SCHEMA_SEMANTIC_KEYS = ("name", "dtype", "semantic_type", "role", "nullable", "unit")


def canonical_hash(value) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"),
                         ensure_ascii=False, allow_nan=False).encode()
    return sha256(encoded).hexdigest()


def frame_version(frame: pd.DataFrame) -> str:
    digest = sha256()
    digest.update(json.dumps([(str(c), str(t)) for c, t in zip(frame.columns, frame.dtypes)]).encode())
    digest.update(pd.util.hash_pandas_object(frame, index=False).values.tobytes())
    return digest.hexdigest()


def semantic_metadata(dataset) -> dict:
    """Explicit allowlist. Presentation/sample metadata is not execution state."""
    schema = [{k: column.get(k) for k in SCHEMA_SEMANTIC_KEYS}
              for column in (dataset.schema or ())]
    schema.sort(key=lambda c: str(c["name"]))
    plan = dict(dataset.derivation_plan or {})
    # Warning prose is presentation. IDs, field selections, ordered steps and
    # the confirmed relationship snapshot are part of the saved execution lineage.
    plan.pop("warnings", None)
    if "included_dataset_ids" in plan:
        plan["included_dataset_ids"] = sorted(plan["included_dataset_ids"])
    if "confirmed_relationships" in plan:
        plan["confirmed_relationships"] = sorted(
            plan["confirmed_relationships"], key=canonical_hash,
        )
    risk = getattr(dataset, "derivation_risk_summary", None) or {}
    return {
        "schema": schema,
        "derivation_type": dataset.derivation_type,
        "derivation_plan": plan,
        "transform_chain": getattr(dataset, "transform_chain", None) or [],
        "source_dataset_ids": sorted(dataset.source_dataset_ids or ()),
        "parent_dataset_id": dataset.parent_dataset_id,
        "grain_declaration": {k: risk.get(k) for k in ("base_grain", "result_grain")},
    }


@dataclass
class AuthoritativeInput:
    """Internal data, never an HTTP/provider input. Frames are request snapshots."""
    dataset_id: str
    frame: pd.DataFrame
    grain: str
    metadata_version: str
    provenance: dict[str, ColumnProvenance] = field(default_factory=dict)
    base_frame: pd.DataFrame | None = None
    base_dataset_id: str | None = None
    metadata: dict = field(default_factory=dict)
    base_metadata: dict = field(default_factory=dict)
    logical_frame: pd.DataFrame | None = None
    base_logical_frame: pd.DataFrame | None = None

    @property
    def version(self):
        # Compatibility for pure in-memory callers; HTTP specs use the complete
        # binding-specific fingerprint generated by prepare_input below.
        return canonical_hash({"frame": frame_version(self.frame), "metadata": self.metadata_version})


def normalize_conversion(values, *, dataset_id, column, reader_contract):
    policy = NORMALIZATION_POLICY
    mapped, tagged = [], []
    counts = {"boolean": 0, "numeric": 0, "string": 0}
    for value in values:
        if isinstance(value, (bool, np.bool_)):
            kind, canonical = "boolean", int(value)
            raw = bool(value)
        elif isinstance(value, Real) and not isinstance(value, bool):
            if not np.isfinite(value) or value not in (0, 1):
                raise DiagnosisError("INVALID_CONVERSION_FLAG")
            kind, canonical, raw = "numeric", int(value), float(value)
        elif isinstance(value, str):
            token = value.strip() if policy.strip_whitespace else value
            token = token.casefold() if policy.case_insensitive else token
            if token in policy.true_strings:
                canonical = 1
            elif token in policy.false_strings:
                canonical = 0
            else:
                raise DiagnosisError("INVALID_CONVERSION_FLAG")
            kind, raw = "string", value
        else:
            raise DiagnosisError("MISSING_OR_INVALID_CONVERSION_FLAG")
        counts[kind] += 1
        tagged.append((kind, raw))
        mapped.append(canonical)
    record = ConversionNormalizationRecord(
        dataset_id=dataset_id, column=column, policy=policy,
        reader_contract=reader_contract, source_logical_hash=canonical_hash(tagged),
        boolean_count=counts["boolean"], numeric_count=counts["numeric"],
        string_count=counts["string"], normalization_applied=counts["string"] > 0,
    )
    return pd.Series(mapped, index=values.index, dtype="int64"), record


def _dataset_fingerprint(dataset_id, frame, metadata, bindings, grain, legacy_metadata):
    schema = metadata.get("schema", [])
    by_name = {c["name"]: c for c in schema}
    field_semantics = [
        {"role": role, "column": column, "schema": by_name.get(column)}
        for role, column in sorted(bindings.items())
    ]
    plan = metadata.get("derivation_plan", {})
    state = DatasetSemanticState(
        dataset_id=dataset_id, frame_hash=frame_version(frame),
        schema_semantic_hash=canonical_hash(schema),
        bound_field_semantics_hash=canonical_hash(field_semantics), grain=grain,
        row_semantics_hash=canonical_hash(metadata.get("grain_declaration", {})),
        derivation_type=metadata.get("derivation_type"),
        derivation_fingerprint=canonical_hash({"plan": plan, "legacy_metadata": legacy_metadata}),
        transform_chain_fingerprint=canonical_hash(metadata.get("transform_chain", [])),
        lineage_source_dataset_ids=tuple(metadata.get("source_dataset_ids", ())),
        base_dataset_id=metadata.get("parent_dataset_id"),
        relationship_snapshot_fingerprint=canonical_hash(plan.get("confirmed_relationships", [])),
    )
    ref = VersionedDatasetRef(dataset_id=dataset_id, version=canonical_hash(state.model_dump(mode="json")))
    return DatasetInputFingerprint(artifact_ref=ref, semantic_state=state)


@dataclass
class PreparedInput:
    frame: pd.DataFrame
    base_frame: pd.DataFrame | None
    fingerprint: AuthoritativeInputFingerprint


def prepare_input(source, bindings) -> PreparedInput:
    """Build the complete snapshot before any recipe/preflight computation."""
    columns = {b.role: b.column for b in bindings}
    frame = source.frame.copy()
    base = source.base_frame.copy() if source.base_frame is not None else None
    records = []
    conversion = columns.get("conversion_flag")
    if source.logical_frame is not None and conversion in frame:
        frame[conversion], record = normalize_conversion(
            source.logical_frame[conversion], dataset_id=source.dataset_id,
            column=conversion, reader_contract=READER_CONTRACT,
        )
        records.append(record)
    base_columns = {}
    for binding in bindings:
        origin = source.provenance.get(binding.column)
        if origin is not None:
            base_columns[binding.role] = origin.source_column
    base_conversion = base_columns.get("conversion_flag")
    if source.base_logical_frame is not None and base_conversion in base:
        base[base_conversion], record = normalize_conversion(
            source.base_logical_frame[base_conversion], dataset_id=source.base_dataset_id,
            column=base_conversion, reader_contract=READER_CONTRACT,
        )
        records.append(record)
    primary = _dataset_fingerprint(
        source.dataset_id, frame, source.metadata, columns, source.grain,
        source.metadata_version if not source.metadata else None,
    )
    base_fp = None
    if base is not None:
        base_fp = _dataset_fingerprint(
            source.base_dataset_id, base, source.base_metadata, base_columns,
            "unique_user", None,
        )
    fingerprint = AuthoritativeInputFingerprint(
        input=primary, base=base_fp,
        source_dataset_refs=(base_fp.artifact_ref,) if base_fp else (),
        projection_semantics=OperatorParameters().projection,
        normalization_policy=NORMALIZATION_POLICY,
        reader_contract=READER_CONTRACT if source.logical_frame is not None else "canonical-in-memory@1",
        normalization_records=tuple(records),
    )
    return PreparedInput(frame, base, fingerprint)
